[package]
name = "qlion"
version = "0.1.0"
authors = ["tigeran <tigeran@tencent.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calamine = "0.16.2"
chrono = "0.4.19"
simple_excel_writer = "0.1.7"
